#open file bashrc
alias gd='git diff'
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gl='git log --oneline'
alias clean='rm -r *.pyc *.swp'
alias cdw='cd /root//LA/La/session_2'
